### PR TITLE
(chore): Delete runtime.txt to ensure the latest runtime environment

### PR DESCRIPTION
**Pull request by duanhongyi**
Delete runtime.txt so you can use the latest runtime environment; the original environment is no longer supported in heroku-18

### CODE REVIEW

**Comment by Cryptophobia** [comment]
Aaah, I see. So the runtime.txt file needs to be removed to allow the application to use the new runtime from the new buildpack. Also, need to change the commit here as well. @duanhongyi

**Comment by kingdonb** [comment]
Should we put it back with the correct version from the new runtime?

**Comment by duanhongyi** [comment]
> Should we put it back with the correct version from the new runtime?

Pthon 3 as a whole is backward compatible, except for some special keywords, such as using async as a variable that makes mistakes in Python 3.7, but it doesn't exist in this use case, so I think you can delete runtime.txt

**Comment by Cryptophobia** [comment]
Agreed with @duanhongyi , we should not be dependent on a particular python version in this test and we should always be testing with the latest if possible. That makes sense since we do not control the buildpack or how the Python Django framework changes.

**Comment by Cryptophobia** [comment]
Merged!

**Pull request merged**
